Revert "Don't check documentation completeness in this stable branch"
This reverts commit 2a0b73c02353a155e473504546a8b7e598da4449.

diff --git a/doc/reference/mission-control-plugins/Makefile.am b/doc/reference/mission-control-plugins/Makefile.am
--- a/doc/reference/mission-control-plugins/Makefile.am
+++ b/doc/reference/mission-control-plugins/Makefile.am
@@ -145,6 +145,14 @@ check-local:
 			echo "$$file missing from $(DOC_MODULE)-docs.sgml"; \
 			err=1; \
 		fi; \
-	done
+	done; \
+	case $(ENABLE_DOC_CHECKS)/$$err in \
+		(yes/1) \
+			echo "Documentation check failed" >&2; \
+			exit $$err; \
+			;; \
+		(*) \
+			exit 0; \
+			;; \
+	esac
 endif
-# ... but don't fail on incomplete documentation, this is a stable branch
