Twisted tests: delete accounts.cfg file for each test

diff --git a/test/twisted/tools/exec-with-log.sh.in b/test/twisted/tools/exec-with-log.sh.in
--- a/test/twisted/tools/exec-with-log.sh.in
+++ b/test/twisted/tools/exec-with-log.sh.in
@@ -2,6 +2,7 @@
 
 cd "@abs_top_builddir@/test/twisted/tools"
 
+# Run Mission Control in a private environment
 export MC_DEBUG=2
 export MC_CHANDLERS_DIR="@abs_top_builddir@/test/twisted/chandlers"
 export MC_MANAGER_DIR="@abs_top_builddir@/test/twisted/managers"
@@ -15,6 +16,17 @@ if test -n "$MISSIONCONTROL_TEST_VALGRIND"; then
 	export G_DEBUG=gc-friendly
 	export G_SLICE=always-malloc
 	MISSIONCONTROL_WRAPPER="valgrind --leak-check=full --num-callers=20"
+fi
+
+# Delete previous Mission Control accounts
+if [ -f "@abs_top_builddir@/test/twisted/accounts/accounts.cfg" ] ; then
+        echo "Delete @abs_top_builddir@/test/twisted/accounts/accounts.cfg"
+        rm -f -- "@abs_top_builddir@/test/twisted/accounts/accounts.cfg"
+fi
+if [ -e "@abs_top_builddir@/test/twisted/accounts/accounts.cfg" ] ; then
+        echo "Error: accounts.cfg file exists:"
+        echo "@abs_top_builddir@/test/twisted/accounts/accounts.cfg"
+        exit 1
 fi
 
 exec $MISSIONCONTROL_WRAPPER @abs_top_builddir@/server/mission-control
